### ISSUE TITLE
Radio tower

### ISSUE THREAD

**Issue by Othello311** [7Cav/I-A-2024#13]
Radio tower main side objective needs to have OPFOR AI added to it that protect it.

**Comment by Othello311** [comment]
Need help with this one.  This is the last "broken" thing before I feel comfortable leaving it on the server.

**Comment by Elemtael** [comment]
Resolved with https://github.com/7Cav/I-A-2024/commit/5dc38d6f736c80ae1b454ae53ec17e1c46bb5e14
