### ISSUE TITLE
Vehicle/Wreck Remover

### ISSUE THREAD

**Issue by Nova4Dayz** [7Cav/I-A-2024#16]
spot on base for deleting wrecks and vehicles to cleanup giving Atlas 4 a vehicle recovery method

**Comment by Othello311** [comment]
Added vehicle despawn area and working code.  Need to add additional area for aviation side.

**Comment by Othello311** [comment]
Working vehicle scrap area in the mission and is marked. Additional area can be added for aviation assets if needed.
